@extends('layouts.front')

@section('page-title', 'Wishlists')


@section('content')
    <!-- Hero -->


    <div id="one-hero-after" class="bg-body-extra-light py-5">

        <div class="content">

            <div class="text-center">
                <h1>Privacy Policy</h1>

            </div>


            <p>Last updated: 8/29/2024</p>
            <p>This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your
                information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p>We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the
                collection and use of information in accordance with this Privacy Policy.</p>

            <h2>Interpretation and Definitions</h2>
            <h3>Interpretation</h3>
            <p>The words of which the initial letter is capitalized have meanings defined under the following conditions.
                The following definitions shall have the same meaning regardless of whether they appear in singular or in
                plural.</p>

            <h3>Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
            <ul>
                <li><strong>"Account"</strong> means a unique account created for You to access our Service or parts of our
                    Service.</li>
                <li><strong>"Business"</strong>, for the purpose of the CCPA (California Consumer Privacy Act), refers to
                    the Company as the legal entity that collects Consumers' personal information and determines the
                    purposes and means of the processing of Consumers' personal information.</li>
                <li><strong>"Company"</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement)
                    refers to Birthday Bonanza.</li>
                <li><strong>"Country"</strong> refers to the United States.</li>
                <li><strong>"Consumer"</strong>, for the purpose of the CCPA, means a natural person who is a California
                    resident.</li>
                <li><strong>"Cookies"</strong> are small files placed on Your computer, mobile device, or any other device
                    by a website, containing the details of Your browsing history.</li>
                <li><strong>"Data Controller"</strong>, for the purposes of the GDPR, refers to the Company as the legal
                    person which alone or jointly with others determines the purposes and means of the processing of
                    Personal Data.</li>
                <li><strong>"Device"</strong> means any device that can access the Service such as a computer, a cell phone,
                    or a digital tablet.</li>
                <li><strong>"Do Not Track"</strong> (DNT) is a concept that allows internet users to control the tracking of
                    their online activities across websites.</li>
                <li><strong>"Personal Data"</strong> means any information that relates to an identified or identifiable
                    individual.</li>
                <li><strong>"Sale"</strong>, for the purpose of the CCPA, means selling or transferring a Consumer's
                    personal information for monetary or other valuable consideration.</li>
                <li><strong>"Service"</strong> refers to the Website.</li>
                <li><strong>"Service Provider"</strong> means any person or entity who processes the data on behalf of the
                    Company.</li>
                <li><strong>"Usage Data"</strong> refers to data collected automatically, either generated by the use of the
                    Service or from the Service infrastructure itself.</li>
                <li><strong>"Website"</strong> refers to Birthday Bonanza, accessible from <a
                        href="https://birthdaybonanza.org">https://birthdaybonanza.org</a>.</li>
                <li><strong>"You"</strong> means the individual accessing or using the Service.</li>
            </ul>

            <h2>Collecting and Using Your Personal Data</h2>
            <h3>Types of Data Collected</h3>
            <h4>Personal Data</h4>
            <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information, such
                as:</p>
            <ul>
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Address, State, Province, ZIP/Postal code, City</li>
                <li>Income tax return</li>
                <li>Usage Data</li>
            </ul>

            <h4>Usage Data</h4>
            <p>Usage Data is collected automatically when using the Service.</p>
            <p>Usage Data may include information such as Your Device's IP address, browser type, browser version, the pages
                of our Service that You visit, and other diagnostic data.</p>

            <h3>Tracking Technologies and Cookies</h3>
            <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain
                information. The technologies we use include:</p>
            <ul>
                <li><strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on Your Device. You can
                    instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent.</li>
                <li><strong>Web Beacons:</strong> Certain sections of our Service and our emails may contain small
                    electronic files known as web beacons that permit the Company to count users who have visited those
                    pages or opened an email.</li>
            </ul>

            <h4>Types of Cookies</h4>
            <ul>
                <li><strong>Necessary / Essential Cookies:</strong> These Cookies are essential to provide You with services
                    available through the Website.</li>
                <li><strong>Cookies Policy / Notice Acceptance Cookies:</strong> These Cookies identify if users have
                    accepted the use of cookies on the Website.</li>
                <li><strong>Functionality Cookies:</strong> These Cookies allow us to remember choices You make when You use
                    the Website.</li>
                <li><strong>Tracking and Performance Cookies:</strong> These Cookies are used to track information about
                    traffic to the Website and how users use the Website.</li>
            </ul>

            <h2>Use of Your Personal Data</h2>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul>
                <li>To provide and maintain our Service.</li>
                <li>To manage Your Account.</li>
                <li>For the performance of a contract.</li>
                <li>To contact You regarding updates or informative communications.</li>
                <li>To provide You with news, special offers, and general information.</li>
                <li>To manage Your requests.</li>
                <li>For business transfers or mergers.</li>
                <li>For other purposes like data analysis and marketing.</li>
            </ul>

            <h2>Retention of Your Personal Data</h2>
            <p>The Company will retain Your Personal Data only for as long as necessary to comply with legal obligations or
                resolve disputes. Usage Data is retained for shorter periods unless used to improve security or
                functionality.</p>

            <h2>Transfer of Your Personal Data</h2>
            <p>Your information, including Personal Data, may be transferred to computers located outside Your jurisdiction
                where data protection laws differ. By providing Personal Data, You agree to this transfer.</p>

            <h2>Disclosure of Your Personal Data</h2>
            <p>We may disclose Your Personal Data under the following conditions:</p>
            <ul>
                <li>If required by law.</li>
                <li>In connection with a business transaction such as a merger.</li>
                <li>To protect the rights and property of the Company.</li>
                <li>To prevent or investigate wrongdoing.</li>
            </ul>

            <h2>Security of Your Personal Data</h2>
            <p>We strive to use commercially acceptable means to protect Your Personal Data, but cannot guarantee its
                absolute security.</p>

            <h2>Your GDPR Privacy Rights</h2>
            <p>If You are within the EU, You have the right to access, update, or delete Your Personal Data, and object to
                or restrict its processing. To exercise these rights, contact Us at any time.</p>


                <h2>CCPA Privacy Policy</h2>
                <p>This privacy notice section for California residents supplements the information contained in Our Privacy Policy and it applies solely to all visitors, users, and others who reside in the State of California.</p>

                <h2>Categories of Personal Information Collected</h2>
                <p>We collect information that identifies, relates to, describes, references, is capable of being associated with, or could reasonably be linked, directly or indirectly, with a particular Consumer or Device. The following is a list of categories of personal information which we may collect or may have been collected from California residents within the last twelve (12) months.</p>
                <p>Please note that the categories and examples provided in the list below are those defined in the CCPA. This does not mean that all examples of that category of personal information were in fact collected by Us, but reflects our good faith belief to the best of our knowledge that some of that information from the applicable category may be and may have been collected.</p>

                <ul>
                    <li><strong>Category A: Identifiers.</strong> Examples: A real name, alias, postal address, unique personal identifier, online identifier, Internet Protocol address, email address, account name, driver's license number, passport number, or other similar identifiers. <em>Collected: Yes.</em></li>

                    <li><strong>Category B: Personal information categories listed in the California Customer Records statute (Cal. Civ. Code § 1798.80(e)).</strong> Examples: A name, signature, Social Security number, physical characteristics or description, address, telephone number, passport number, driver's license or state identification card number, insurance policy number, education, employment, employment history, bank account number, credit card number, debit card number, or any other financial information, medical information, or health insurance information. <em>Collected: Yes.</em></li>

                    <li><strong>Category C: Protected classification characteristics under California or federal law.</strong> Examples: Age (40 years or older), race, color, ancestry, national origin, citizenship, religion or creed, marital status, medical condition, physical or mental disability, sex (including gender, gender identity, gender expression, pregnancy or childbirth and related medical conditions), sexual orientation, veteran or military status, genetic information (including familial genetic information). <em>Collected: Yes, Age and Sex.</em></li>

                    <li><strong>Category D: Commercial information.</strong> Examples: Records and history of products or services purchased or considered. <em>Collected: No.</em></li>

                    <li><strong>Category E: Biometric information.</strong> Examples: Genetic, physiological, behavioral, and biological characteristics, or activity patterns used to extract a template or other identifier or identifying information, such as, fingerprints, faceprints, and voiceprints, iris or retina scans, keystroke, gait, or other physical patterns, and sleep, health, or exercise data. <em>Collected: No.</em></li>

                    <li><strong>Category F: Internet or other similar network activity.</strong> Examples: Interaction with our Service or advertisement. <em>Collected: Yes.</em></li>

                    <li><strong>Category G: Geolocation data.</strong> Examples: Approximate physical location. <em>Collected: No.</em></li>

                    <li><strong>Category H: Sensory data.</strong> Examples: Audio, electronic, visual, thermal, olfactory, or similar information. <em>Collected: No.</em></li>

                    <li><strong>Category I: Professional or employment-related information.</strong> Examples: Current or past job history or performance evaluations. <em>Collected: No.</em></li>

                    <li><strong>Category J: Non-public education information (per the Family Educational Rights and Privacy Act (20 U.S.C. Section 1232g, 34 C.F.R. Part 99)).</strong> Examples: Education records directly related to a student maintained by an educational institution or party acting on its behalf. <em>Collected: No.</em></li>

                    <li><strong>Category K: Inferences drawn from other personal information.</strong> Examples: Profile reflecting a person's preferences, characteristics, psychological trends, predispositions, behavior, attitudes, intelligence, abilities, and aptitudes. <em>Collected: No.</em></li>
                </ul>

                <h2>Sources of Personal Information</h2>
                <p>We obtain the categories of personal information listed above from the following categories of sources:</p>
                <ul>
                    <li>Directly from You. For example, from the forms You complete on our Service, preferences You express or provide through our Service, or from Your purchases on our Service.</li>
                    <li>Indirectly from You. For example, from observing Your activity on our Service.</li>
                    <li>Automatically from You. For example, through cookies We or our Service Providers set on Your Device as You navigate through our Service.</li>
                    <li>From Service Providers. For example, third-party vendors to monitor and analyze the use of our Service.</li>
                </ul>

                <h2>Use of Personal Information for Business Purposes or Commercial Purposes</h2>
                <p>We may use or disclose personal information We collect for "business purposes" or "commercial purposes" as defined under the CCPA, which may include:</p>
                <ul>
                    <li>To operate our Service and provide You with our Service.</li>
                    <li>To provide You with support and respond to Your inquiries.</li>
                    <li>To fulfill or meet the reason You provided the information.</li>
                    <li>To respond to law enforcement requests.</li>
                    <li>As described to You when collecting Your personal information or as otherwise set forth in the CCPA.</li>
                    <li>For internal administrative and auditing purposes.</li>
                    <li>To detect security incidents and protect against malicious, fraudulent, or illegal activity.</li>
                </ul>

                <h2>Disclosure of Personal Information for Business Purposes or Commercial Purposes</h2>
                <p>We may use or disclose the following categories of personal information for business or commercial purposes:</p>
                <ul>
                    <li>Category A: Identifiers</li>
                    <li>Category B: Personal information categories listed in the California Customer Records statute</li>
                    <li>Category D: Commercial information</li>
                    <li>Category F: Internet or other similar network activity</li>
                </ul>

                <h2>Sale of Personal Information</h2>
                <p>As defined in the CCPA, "sell" and "sale" mean selling, renting, releasing, disclosing, disseminating, making available, transferring, or otherwise communicating a consumer's personal information for valuable consideration.</p>
                <p>We do not sell the following categories of personal information:</p>
                <ul>
                    <li>Category A: Identifiers</li>
                    <li>Category B: Personal information categories listed in the California Customer Records statute</li>
                    <li>Category D: Commercial information</li>
                    <li>Category F: Internet or other similar network activity</li>
                </ul>

                <h2>Your Rights under the CCPA</h2>
                <p>The CCPA provides California residents with specific rights regarding their personal information, including:</p>
                <ul>
                    <li>The right to notice</li>
                    <li>The right to request information about our collection, use, sale, disclosure, or share of personal information</li>
                    <li>The right to say no to the sale of Personal Data (opt-out)</li>
                    <li>The right to delete Personal Data</li>
                    <li>The right not to be discriminated against for exercising consumer rights</li>
                </ul>

                <h2>Exercising Your CCPA Data Protection Rights</h2>
                <p>If you are a California resident, you can contact us to exercise your CCPA rights by emailing: <a href="mailto:contact@birthdaybonanza.org">contact@birthdaybonanza.org</a></p>

                <h2>"Do Not Track" Policy as Required by California Online Privacy Protection Act (CalOPPA)</h2>
                <p>Our Service does not respond to Do Not Track signals.</p>

                <h2>Children's Privacy</h2>
                <p>Our Service does not address anyone under the age of 13. If you are a parent or guardian and are aware that your child has provided us with Personal Data, please contact us.</p>

                <h2>Changes to this Privacy Policy</h2>
                <p>We may update Our Privacy Policy from time to time. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

                <h2>Contact Us</h2>
                <p>If you have any questions about this Privacy Policy, You can contact us by sending an email to <a href="mailto:contact@birthdaybonanza.org">contact@birthdaybonanza.org</a>.</p>


        </div>
    </div>

@endsection
